# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'buttons.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1352, 743)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(40, 40, 281, 51))
        font = QtGui.QFont()
        font.setFamily("KG How Many Times")
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(248, 54, 54);")
        self.pushButton.setAutoDefault(True)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 110, 281, 51))
        font = QtGui.QFont()
        font.setFamily("KG How Many Times")
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 188, 30);")
        self.pushButton_2.setAutoDefault(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_10 = QtWidgets.QPushButton(Dialog)
        self.pushButton_10.setGeometry(QtCore.QRect(360, 40, 281, 51))
        font = QtGui.QFont()
        font.setFamily("KG How Many Times")
        font.setPointSize(16)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(248, 54, 54);")
        self.pushButton_10.setAutoDefault(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_12 = QtWidgets.QPushButton(Dialog)
        self.pushButton_12.setGeometry(QtCore.QRect(360, 110, 281, 51))
        font = QtGui.QFont()
        font.setFamily("KG How Many Times")
        font.setPointSize(16)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 188, 30);")
        self.pushButton_12.setAutoDefault(True)
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_19 = QtWidgets.QPushButton(Dialog)
        self.pushButton_19.setGeometry(QtCore.QRect(680, 40, 281, 51))
        font = QtGui.QFont()
        font.setFamily("KG How Many Times")
        font.setPointSize(16)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(248, 54, 54);")
        self.pushButton_19.setAutoDefault(True)
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_22 = QtWidgets.QPushButton(Dialog)
        self.pushButton_22.setGeometry(QtCore.QRect(680, 180, 281, 51))
        font = QtGui.QFont()
        font.setFamily("KG How Many Times")
        font.setPointSize(16)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setStyleSheet("background-color: rgb(95, 191, 50);border-radius: 10px;")
        self.pushButton_22.setAutoDefault(True)
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 180, 281, 51))
        font = QtGui.QFont()
        font.setFamily("KG How Many Times")
        font.setPointSize(16)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(95, 191, 50);border-radius: 10px;")
        self.pushButton_3.setAutoDefault(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_13 = QtWidgets.QPushButton(Dialog)
        self.pushButton_13.setGeometry(QtCore.QRect(360, 180, 281, 51))
        font = QtGui.QFont()
        font.setFamily("KG How Many Times")
        font.setPointSize(16)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("background-color: rgb(95, 191, 50);border-radius: 10px;")
        self.pushButton_13.setAutoDefault(True)
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_21 = QtWidgets.QPushButton(Dialog)
        self.pushButton_21.setGeometry(QtCore.QRect(680, 110, 281, 51))
        font = QtGui.QFont()
        font.setFamily("KG How Many Times")
        font.setPointSize(16)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setStyleSheet("background-color: rgb(95, 191, 50);border-radius: 10px;")
        self.pushButton_21.setAutoDefault(True)
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_23 = QtWidgets.QPushButton(Dialog)
        self.pushButton_23.setGeometry(QtCore.QRect(40, 260, 281, 51))
        font = QtGui.QFont()
        font.setFamily("KG How Many Times")
        font.setPointSize(16)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(82, 180, 255);")
        self.pushButton_23.setAutoDefault(True)
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(530, 400, 31, 31))
        self.pushButton_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.pushButton_4.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/icons8-exit-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setIconSize(QtCore.QSize(31, 31))
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Order 200"))
        self.pushButton_2.setText(_translate("Dialog", "Order 203"))
        self.pushButton_10.setText(_translate("Dialog", "Order 201"))
        self.pushButton_12.setText(_translate("Dialog", "Order 204"))
        self.pushButton_19.setText(_translate("Dialog", "Order 202"))
        self.pushButton_22.setText(_translate("Dialog", "Order 209"))
        self.pushButton_3.setText(_translate("Dialog", "Order 206"))
        self.pushButton_13.setText(_translate("Dialog", "Order 207"))
        self.pushButton_21.setText(_translate("Dialog", "Order 205"))
        self.pushButton_23.setText(_translate("Dialog", "Order 210"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
