# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from functools import partial

filePath = "C:/Users/bgarman/Downloads"

class Ui_MainUI(object):

        def ExitScreen(self, MainWindow):
                MainWindow.close()

        
        def setupUi(self, MainUI):
                MainUI.setObjectName("MainUI")
                self.AllWidgets = QtWidgets.QWidget(MainUI)
                self.AllWidgets.setObjectName("AllWidgets")
                self.gridLayout_3 = QtWidgets.QGridLayout(self.AllWidgets)
                self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
                self.gridLayout_3.setObjectName("gridLayout_3")
                self.MainUISnapGrid = QtWidgets.QVBoxLayout()
                self.MainUISnapGrid.setSpacing(0)
                self.MainUISnapGrid.setObjectName("MainUISnapGrid")
                self.TopUILayout = QtWidgets.QHBoxLayout()
                self.TopUILayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
                self.TopUILayout.setSpacing(0)
                self.TopUILayout.setObjectName("TopUILayout")
                self.BackgroundLogo = QtWidgets.QLabel(self.AllWidgets)
                self.BackgroundLogo.setMinimumSize(QtCore.QSize(0, 0))
                self.BackgroundLogo.setPixmap(QtGui.QPixmap(filePath + "/test-removebg-preview.png"))
                self.BackgroundLogo.setAlignment(QtCore.Qt.AlignCenter)
                self.BackgroundLogo.setObjectName("BackgroundLogo")
                self.TopUILayout.addWidget(self.BackgroundLogo)
                self.OrderDetailsFrame = QtWidgets.QFrame(self.AllWidgets)
                self.OrderDetailsFrame.setMinimumSize(QtCore.QSize(300, 0))
                self.OrderDetailsFrame.setMaximumSize(QtCore.QSize(300, 16777215))
                self.OrderDetailsFrame.setStyleSheet("background-color: rgb(207, 207, 207);")
                self.OrderDetailsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.OrderDetailsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.OrderDetailsFrame.setObjectName("OrderDetailsFrame")
                self.gridLayout_2 = QtWidgets.QGridLayout(self.OrderDetailsFrame)
                self.gridLayout_2.setObjectName("gridLayout_2")
                self.OrderNumberLabel = QtWidgets.QLabel(self.OrderDetailsFrame)
                self.OrderNumberLabel.setStyleSheet("font: 20pt \"KG LET HER GO SOLID\";\n"
        "text-decoration: underline;")
                self.OrderNumberLabel.setAlignment(QtCore.Qt.AlignCenter)
                self.OrderNumberLabel.setObjectName("OrderNumberLabel")
                self.gridLayout_2.addWidget(self.OrderNumberLabel, 0, 0, 1, 1)
                self.ReprintTicketButton = QtWidgets.QPushButton(self.OrderDetailsFrame)
                self.ReprintTicketButton.setMinimumSize(QtCore.QSize(0, 40))
                font = QtGui.QFont()
                font.setFamily("KG How Many Times")
                font.setPointSize(14)
                self.ReprintTicketButton.setFont(font)
                self.ReprintTicketButton.setStyleSheet("border-radius: 10px;\n"
        "background-color: rgb(132, 134, 144);\n"
        "")
                self.ReprintTicketButton.setAutoDefault(True)
                self.ReprintTicketButton.setObjectName("ReprintTicketButton")
                self.gridLayout_2.addWidget(self.ReprintTicketButton, 10, 0, 1, 1)
                self.DetailsTitleLabel = QtWidgets.QLabel(self.OrderDetailsFrame)
                self.DetailsTitleLabel.setStyleSheet("font: 14pt \"KG How Many Times\";\n"
        "text-decoration: underline;\n"
        "")
                self.DetailsTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
                self.DetailsTitleLabel.setObjectName("DetailsTitleLabel")
                self.gridLayout_2.addWidget(self.DetailsTitleLabel, 1, 0, 1, 1)
                self.ReprintStickerButton = QtWidgets.QPushButton(self.OrderDetailsFrame)
                self.ReprintStickerButton.setMinimumSize(QtCore.QSize(0, 40))
                font = QtGui.QFont()
                font.setFamily("KG How Many Times")
                font.setPointSize(14)
                self.ReprintStickerButton.setFont(font)
                self.ReprintStickerButton.setStyleSheet("border-radius: 10px;\n"
        "background-color: rgb(132, 134, 144);\n"
        "")
                self.ReprintStickerButton.setAutoDefault(True)
                self.ReprintStickerButton.setObjectName("ReprintStickerButton")
                self.gridLayout_2.addWidget(self.ReprintStickerButton, 8, 0, 1, 1)
                self.ItemsTitleLabel = QtWidgets.QLabel(self.OrderDetailsFrame)
                self.ItemsTitleLabel.setStyleSheet("font: 14pt \"KG How Many Times\";\n"
        "text-decoration: underline;\n"
        "")
                self.ItemsTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
                self.ItemsTitleLabel.setObjectName("ItemsTitleLabel")
                self.gridLayout_2.addWidget(self.ItemsTitleLabel, 5, 0, 1, 1)
                self.ItemsOrderedTableWidget = QtWidgets.QTableWidget(self.OrderDetailsFrame)
                font = QtGui.QFont()
                font.setFamily("KG How Many Times")
                font.setPointSize(14)
                self.ItemsOrderedTableWidget.setFont(font)
                self.ItemsOrderedTableWidget.setStyleSheet("border: none;")
                self.ItemsOrderedTableWidget.setGridStyle(QtCore.Qt.NoPen)
                self.ItemsOrderedTableWidget.setObjectName("ItemsOrderedTableWidget")
                self.ItemsOrderedTableWidget.setColumnCount(1)
                self.ItemsOrderedTableWidget.setRowCount(0)
                item = QtWidgets.QTableWidgetItem()
                self.ItemsOrderedTableWidget.setHorizontalHeaderItem(0, item)
                self.ItemsOrderedTableWidget.horizontalHeader().setVisible(False)
                self.ItemsOrderedTableWidget.horizontalHeader().setDefaultSectionSize(256)
                self.ItemsOrderedTableWidget.verticalHeader().setVisible(False)
                self.ItemsOrderedTableWidget.verticalHeader().setDefaultSectionSize(30)
                self.gridLayout_2.addWidget(self.ItemsOrderedTableWidget, 6, 0, 1, 1)
                spacerItem = QtWidgets.QSpacerItem(90, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
                self.gridLayout_2.addItem(spacerItem, 7, 0, 1, 1)
                self.OrderDetailsInfo = QtWidgets.QSplitter(self.OrderDetailsFrame)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.OrderDetailsInfo.sizePolicy().hasHeightForWidth())
                self.OrderDetailsInfo.setSizePolicy(sizePolicy)
                self.OrderDetailsInfo.setOrientation(QtCore.Qt.Vertical)
                self.OrderDetailsInfo.setObjectName("OrderDetailsInfo")
                self.DatePlacedLabel = QtWidgets.QLabel(self.OrderDetailsInfo)
                self.DatePlacedLabel.setStyleSheet("font: 14pt \"KG How Many Times\";")
                self.DatePlacedLabel.setObjectName("DatePlacedLabel")
                self.TimePlacedLabel = QtWidgets.QLabel(self.OrderDetailsInfo)
                self.TimePlacedLabel.setStyleSheet("font: 14pt \"KG How Many Times\";")
                self.TimePlacedLabel.setObjectName("TimePlacedLabel")
                self.PaymentMethodLabel = QtWidgets.QLabel(self.OrderDetailsInfo)
                self.PaymentMethodLabel.setStyleSheet("font: 14pt \"KG How Many Times\";")
                self.PaymentMethodLabel.setObjectName("PaymentMethodLabel")
                self.TimeCollectionLabel = QtWidgets.QLabel(self.OrderDetailsInfo)
                self.TimeCollectionLabel.setStyleSheet("font: 14pt \"KG How Many Times\";")
                self.TimeCollectionLabel.setObjectName("TimeCollectionLabel")
                self.StatusLabel = QtWidgets.QLabel(self.OrderDetailsInfo)
                self.StatusLabel.setStyleSheet("font: 14pt \"KG How Many Times\";")
                self.StatusLabel.setObjectName("StatusLabel")
                self.gridLayout_2.addWidget(self.OrderDetailsInfo, 2, 0, 1, 1)
                spacerItem1 = QtWidgets.QSpacerItem(60, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
                self.gridLayout_2.addItem(spacerItem1, 4, 0, 1, 1)
                self.TopUILayout.addWidget(self.OrderDetailsFrame)
                self.MainUISnapGrid.addLayout(self.TopUILayout)
                self.BottomUILayout = QtWidgets.QFrame(self.AllWidgets)
                self.BottomUILayout.setMaximumSize(QtCore.QSize(16777215, 100))
                self.BottomUILayout.setStyleSheet("background-color: rgb(207, 207, 207);\n"
        "border-color: rgb(207, 207, 207);")
                self.BottomUILayout.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.BottomUILayout.setFrameShadow(QtWidgets.QFrame.Raised)
                self.BottomUILayout.setObjectName("BottomUILayout")
                self.gridLayout = QtWidgets.QGridLayout(self.BottomUILayout)
                self.gridLayout.setObjectName("gridLayout")
                self.BottomSpacer = QtWidgets.QSplitter(self.BottomUILayout)
                self.BottomSpacer.setOrientation(QtCore.Qt.Horizontal)
                self.BottomSpacer.setObjectName("BottomSpacer")
                self.TitleLabel = QtWidgets.QLabel(self.BottomSpacer)
                self.TitleLabel.setStyleSheet("font: 20pt \"KG LET HER GO SOLID\";")
                self.TitleLabel.setAlignment(QtCore.Qt.AlignCenter)
                self.TitleLabel.setObjectName("TitleLabel")
                self.MenuBar = QtWidgets.QSplitter(self.BottomSpacer)
                self.MenuBar.setMinimumSize(QtCore.QSize(290, 0))
                self.MenuBar.setMaximumSize(QtCore.QSize(214, 31))
                self.MenuBar.setOrientation(QtCore.Qt.Horizontal)
                self.MenuBar.setChildrenCollapsible(True)
                self.MenuBar.setObjectName("MenuBar")
                self.MenuSplitter5 = QtWidgets.QFrame(self.MenuBar)
                self.MenuSplitter5.setMaximumSize(QtCore.QSize(1, 50))
                self.MenuSplitter5.setStyleSheet("background-color: rgb(141, 141, 141);")
                self.MenuSplitter5.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.MenuSplitter5.setFrameShadow(QtWidgets.QFrame.Raised)
                self.MenuSplitter5.setObjectName("MenuSplitter5")
                self.printersConnected = QtWidgets.QPushButton(self.MenuBar)
                self.printersConnected.setMaximumSize(QtCore.QSize(31, 31))
                self.printersConnected.setText("")
                self.printersConnected.setIcon(QtGui.QIcon(filePath + "/icons8-label-printer-96.png"))
                self.printersConnected.setStyleSheet("background-color: rgba(207, 207, 207, 0); border: none;")
                self.printersConnected.setIconSize(QtCore.QSize(31, 31))
                self.printersConnected.setObjectName("printersConnected")
                self.MenuSplitter4 = QtWidgets.QFrame(self.MenuBar)
                self.MenuSplitter4.setMaximumSize(QtCore.QSize(1, 50))
                self.MenuSplitter4.setStyleSheet("background-color: rgb(141, 141, 141);")
                self.MenuSplitter4.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.MenuSplitter4.setFrameShadow(QtWidgets.QFrame.Raised)
                self.MenuSplitter4.setObjectName("MenuSplitter4")
                self.managerPortalButton = QtWidgets.QPushButton(self.MenuBar)
                self.managerPortalButton.setMaximumSize(QtCore.QSize(31, 31))
                self.managerPortalButton.setText("")
                self.managerPortalButton.setIcon(QtGui.QIcon(filePath + "/icons8-coins-128.png"))
                self.managerPortalButton.setStyleSheet("background-color: rgba(207, 207, 207, 0); border: none;")
                self.managerPortalButton.setIconSize(QtCore.QSize(31, 31))
                self.managerPortalButton.setObjectName("managerPortalButton")
                self.MenuSplitter3 = QtWidgets.QFrame(self.MenuBar)
                self.MenuSplitter3.setMaximumSize(QtCore.QSize(1, 50))
                self.MenuSplitter3.setStyleSheet("background-color: rgb(141, 141, 141);")
                self.MenuSplitter3.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.MenuSplitter3.setFrameShadow(QtWidgets.QFrame.Raised)
                self.MenuSplitter3.setObjectName("MenuSplitter3")
                self.stockButton = QtWidgets.QPushButton(self.MenuBar)
                self.stockButton.setMaximumSize(QtCore.QSize(31, 31))
                self.stockButton.setText("")
                self.stockButton.setIcon(QtGui.QIcon(filePath + "/icons8-clipboard-160.png"))
                self.stockButton.setStyleSheet("background-color: rgba(207, 207, 207, 0); border: none;")
                self.stockButton.setIconSize(QtCore.QSize(31, 31))
                self.stockButton.setObjectName("stockButton")
                self.MenuSplitter2 = QtWidgets.QFrame(self.MenuBar)
                self.MenuSplitter2.setMaximumSize(QtCore.QSize(1, 50))
                self.MenuSplitter2.setStyleSheet("background-color: rgb(141, 141, 141);")
                self.MenuSplitter2.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.MenuSplitter2.setFrameShadow(QtWidgets.QFrame.Raised)
                self.MenuSplitter2.setObjectName("MenuSplitter2")
                self.wifiButton = QtWidgets.QPushButton(self.MenuBar)
                self.wifiButton.setMaximumSize(QtCore.QSize(31, 31))
                self.wifiButton.setText("")
                self.wifiButton.setIcon(QtGui.QIcon(filePath + "/icons8-wi-fi-96.png"))
                self.wifiButton.setStyleSheet("background-color: rgba(207, 207, 207, 0); border: none;")
                self.wifiButton.setIconSize(QtCore.QSize(31, 31))
                self.wifiButton.setObjectName("wifiButton")
                self.MenuSplitter1 = QtWidgets.QFrame(self.MenuBar)
                self.MenuSplitter1.setMaximumSize(QtCore.QSize(1, 50))
                self.MenuSplitter1.setStyleSheet("background-color: rgb(141, 141, 141);")
                self.MenuSplitter1.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.MenuSplitter1.setFrameShadow(QtWidgets.QFrame.Raised)
                self.MenuSplitter1.setObjectName("MenuSplitter1")
                self.exitButton = QtWidgets.QPushButton(self.MenuBar)
                self.exitButton.setMaximumSize(QtCore.QSize(31, 31))
                self.exitButton.setText("")
                self.exitButton.setIcon(QtGui.QIcon(filePath + "/icons8-exit-100.png"))
                self.exitButton.setIconSize(QtCore.QSize(31, 31))
                self.exitButton.setStyleSheet("background-color: rgba(207, 207, 207, 0); border: none;")
                self.exitButton.setObjectName("exitButton")
                self.exitButton.clicked.connect(partial(self.ExitScreen, MainUI))
                self.gridLayout.addWidget(self.BottomSpacer, 1, 0, 1, 1)
                spacerItem2 = QtWidgets.QSpacerItem(20, 7, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
                self.gridLayout.addItem(spacerItem2, 0, 0, 1, 1)
                spacerItem3 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
                self.gridLayout.addItem(spacerItem3, 2, 0, 1, 1)
                self.MainUISnapGrid.addWidget(self.BottomUILayout)
                self.gridLayout_3.addLayout(self.MainUISnapGrid, 0, 0, 1, 1)
                MainUI.setCentralWidget(self.AllWidgets)

                self.retranslateUi(MainUI)
                QtCore.QMetaObject.connectSlotsByName(MainUI)
                

                
                        


                

        def retranslateUi(self, MainUI):
                _translate = QtCore.QCoreApplication.translate
                MainUI.setWindowTitle(_translate("MainUI", "MainWindow"))
                self.OrderNumberLabel.setText(_translate("MainUI", "ORDER - 201"))
                self.ReprintTicketButton.setText(_translate("MainUI", "Reprint Order Ticket"))
                self.DetailsTitleLabel.setText(_translate("MainUI", "DETAILS"))
                self.ReprintStickerButton.setText(_translate("MainUI", "Reprint Sticker Label"))
                self.ItemsTitleLabel.setText(_translate("MainUI", "ITEMS"))
                item = self.ItemsOrderedTableWidget.horizontalHeaderItem(0)
                item.setText(_translate("MainUI", "New Column"))
                self.DatePlacedLabel.setText(_translate("MainUI", "Date:                  01/04/2020"))
                self.TimePlacedLabel.setText(_translate("MainUI", "Time:                  12:30"))
                self.PaymentMethodLabel.setText(_translate("MainUI", "Time:                  12:30"))
                self.TimeCollectionLabel.setText(_translate("MainUI", "Collection Time:      14:30"))
                self.StatusLabel.setText(_translate("MainUI", "Status:                Waiting"))
                self.TitleLabel.setText(_translate("MainUI", "BREAD OVEN - KITCHEN MANAGEMENT SYSTEM"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainUI = QtWidgets.QMainWindow()
    ui = Ui_MainUI()
    ui.setupUi(MainUI)
    MainUI.showFullScreen()
    ui.GenerateOrders()
    sys.exit(app.exec_())
