# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from functools import partial

filePath = "C:/Users/bgarman/Downloads/"

class Ui_MainWindow(object):

    def buttonClicked(self, MainWindow):
        MainWindow.close()
        print("clicked")

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1403, 897)()
        self.MainUI = QtWidgets.QWidget(MainWindow)
        self.MainUI.setObjectName("MainUI")
        self.MainUISnap = QtWidgets.QGridLayout(self.MainUI)
        self.MainUISnap.setContentsMargins(0, 0, 0, 0)
        self.MainUISnap.setObjectName("MainUISnap")
        self.MainUIVerticalSnap = QtWidgets.QVBoxLayout()
        self.MainUIVerticalSnap.setSpacing(0)
        self.MainUIVerticalSnap.setObjectName("MainUIVerticalSnap")
        self.TopHalfUI = QtWidgets.QHBoxLayout()
        self.TopHalfUI.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.TopHalfUI.setSpacing(0)
        self.TopHalfUI.setObjectName("TopHalfUI")
        self.BackgroundLogo = QtWidgets.QLabel(self.MainUI)
        self.BackgroundLogo.setMinimumSize(QtCore.QSize(0, 0))
        self.BackgroundLogo.setPixmap(QtGui.QPixmap(filePath + "test-removebg-preview.png"))
        self.BackgroundLogo.setAlignment(QtCore.Qt.AlignCenter)
        self.BackgroundLogo.setObjectName("BackgroundLogo")
        self.TopHalfUI.addWidget(self.BackgroundLogo)
        self.DetailsPage = QtWidgets.QFrame(self.MainUI)
        self.DetailsPage.setMinimumSize(QtCore.QSize(300, 0))
        self.DetailsPage.setMaximumSize(QtCore.QSize(300, 16777215))
        self.DetailsPage.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.DetailsPage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DetailsPage.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DetailsPage.setObjectName("DetailsPage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.DetailsPage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.DetailsPage)
        self.label_3.setStyleSheet("font: 20pt \"KG LET HER GO SOLID\";\n"
"text-decoration: underline;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.DetailsPage)
        self.pushButton_14.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("KG How Many Times")
        font.setPointSize(14)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(132, 134, 144);\n"
"")
        self.pushButton_14.setAutoDefault(True)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_2.addWidget(self.pushButton_14, 10, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.DetailsPage)
        self.label_10.setStyleSheet("font: 14pt \"KG How Many Times\";\n"
"text-decoration: underline;\n"
"")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 0, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.DetailsPage)
        self.pushButton_11.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("KG How Many Times")
        font.setPointSize(14)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(132, 134, 144);\n"
"")
        self.pushButton_11.setAutoDefault(True)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_2.addWidget(self.pushButton_11, 8, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.DetailsPage)
        self.label_9.setStyleSheet("font: 14pt \"KG How Many Times\";\n"
"text-decoration: underline;\n"
"")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 5, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.DetailsPage)
        font = QtGui.QFont()
        font.setFamily("KG How Many Times")
        font.setPointSize(14)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("border: none;")
        self.tableWidget.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(256)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.gridLayout_2.addWidget(self.tableWidget, 6, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(90, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem, 7, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.DetailsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label_4 = QtWidgets.QLabel(self.splitter)
        self.label_4.setStyleSheet("font: 14pt \"KG How Many Times\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.splitter)
        self.label_5.setStyleSheet("font: 14pt \"KG How Many Times\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.splitter)
        self.label_6.setStyleSheet("font: 14pt \"KG How Many Times\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.splitter)
        self.label_7.setStyleSheet("font: 14pt \"KG How Many Times\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.splitter)
        self.label_8.setStyleSheet("font: 14pt \"KG How Many Times\";")
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.splitter, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(60, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem1, 4, 0, 1, 1)
        self.TopHalfUI.addWidget(self.DetailsPage)
        self.MainUIVerticalSnap.addLayout(self.TopHalfUI)
        self.frame_2 = QtWidgets.QFrame(self.MainUI)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_2.setStyleSheet("background-color: rgb(207, 207, 207);\n"
"border-color: rgb(207, 207, 207);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter_3 = QtWidgets.QSplitter(self.frame_2)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.label_2 = QtWidgets.QLabel(self.splitter_3)
        self.label_2.setStyleSheet("font: 20pt \"KG LET HER GO SOLID\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setMinimumSize(QtCore.QSize(290, 0))
        self.splitter_2.setMaximumSize(QtCore.QSize(214, 31))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setChildrenCollapsible(True)
        self.splitter_2.setObjectName("splitter_2")
        self.frame_7 = QtWidgets.QFrame(self.splitter_2)
        self.frame_7.setMaximumSize(QtCore.QSize(1, 50))
        self.frame_7.setStyleSheet("background-color: rgb(141, 141, 141);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_15 = QtWidgets.QLabel(self.splitter_2)
        self.label_15.setMaximumSize(QtCore.QSize(31, 31))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap(filePath + "icons8-label-printer-96.png"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.frame_6 = QtWidgets.QFrame(self.splitter_2)
        self.frame_6.setMaximumSize(QtCore.QSize(1, 50))
        self.frame_6.setStyleSheet("background-color: rgb(141, 141, 141);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_14 = QtWidgets.QLabel(self.splitter_2)
        self.label_14.setMaximumSize(QtCore.QSize(31, 31))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap(filePath + "icons8-coins-128.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.frame_5 = QtWidgets.QFrame(self.splitter_2)
        self.frame_5.setMaximumSize(QtCore.QSize(1, 50))
        self.frame_5.setStyleSheet("background-color: rgb(141, 141, 141);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_13 = QtWidgets.QLabel(self.splitter_2)
        self.label_13.setMaximumSize(QtCore.QSize(31, 31))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap(filePath + "icons8-clipboard-160.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.frame_4 = QtWidgets.QFrame(self.splitter_2)
        self.frame_4.setMaximumSize(QtCore.QSize(1, 50))
        self.frame_4.setStyleSheet("background-color: rgb(141, 141, 141);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_12 = QtWidgets.QLabel(self.splitter_2)
        self.label_12.setMaximumSize(QtCore.QSize(31, 31))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap(filePath + "icons8-wi-fi-96.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.frame_3 = QtWidgets.QFrame(self.splitter_2)
        self.frame_3.setMaximumSize(QtCore.QSize(1, 50))
        self.frame_3.setStyleSheet("background-color: rgb(141, 141, 141);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_11 = QtWidgets.QPushButton(self.splitter_2)
        self.label_11.setMaximumSize(QtCore.QSize(31, 31))
        self.label_11.setText("")
        self.label_11.setIcon(QtGui.QIcon(filePath + "icons8-exit-100.png"))
        self.label_11.setIconSize(QtCore.QSize(31, 31))
        self.label_11.setStyleSheet("background-color: rgba(207, 207, 207, 0); border: none;")
        self.label_11.clicked.connect(partial(self.buttonClicked, MainWindow))
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.splitter_3, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 7, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 2, 0, 1, 1)
        self.MainUIVerticalSnap.addWidget(self.frame_2)
        self.MainUISnap.addLayout(self.MainUIVerticalSnap, 0, 0, 1, 1)
        MainWindow.setMainUI(self.MainUI)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "ORDER - 201"))
        self.pushButton_14.setText(_translate("MainWindow", "Reprint Order Ticket"))
        self.label_10.setText(_translate("MainWindow", "DETAILS"))
        self.pushButton_11.setText(_translate("MainWindow", "Reprint Sticker Label"))
        self.label_9.setText(_translate("MainWindow", "ITEMS"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "- White Baguette"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "        - Cucumber, Cheese"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "        - Salad Cream"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "- Cheese & Onion Walkers"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("MainWindow", "- Coca Cola"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_4.setText(_translate("MainWindow", "Date:                  01/04/2020"))
        self.label_5.setText(_translate("MainWindow", "Time:                  12:30"))
        self.label_6.setText(_translate("MainWindow", "Time:                  12:30"))
        self.label_7.setText(_translate("MainWindow", "Collection Time:      14:30"))
        self.label_8.setText(_translate("MainWindow", "Status:                Waiting"))
        self.label_2.setText(_translate("MainWindow", "BREAD OVEN - KITCHEN MANAGEMENT SYSTEM"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.showFullScreen()
    sys.exit(app.exec_())
